default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock


test:
  <<: *default
  database: pictweet_test

development:
  <<: *default
  database: chat-space_development

production:
  <<: *default
  database: chat-space_production